# .graphclientrc.yml
sources:
  - name: swapos-polygon-mumbai
    handler:
      graphql:
        endpoint: https://api.thegraph.com/subgraphs/name/mprasanjith/swapos-polygon-mumbai
    transforms:
      - blockTracking:
          validateSchema: true

plugins:
  - pollingLive:
      defaultInterval: 1000

documents:
  - ./src/queries/getAll.graphql
